### ISSUE TITLE
Provide easier way to configure capabilities or browser options

### ISSUE THREAD

**Issue by ezagdd** [uezo/TinySeleniumVBA#28]
TinySeleniumVBA WebDriver.cls に対して、Capabilities, DesiredCapabilitiesを組立てるメソッドをテスト的に作ってみました。
ブラウザは、ChromeとEdgeに限定です。
別途Classモジュールを作った方がスマートかもしれません。

関連記事：https://qiita.com/uezo/items/66e20b064ffd5f239b9a
　　　　　Qiita @ezagdd 2021-08-28 14:01

WedDriver.cls の Edge関数と Chrome関数に対し、ブラウザ判定用に１行追加

```
Public Sub Edge(・・・・・
　　　：
    DriverName = "msedgedriver"         '2021/9/20 ishi add
End Sub

Public Sub Chrome(・・・・・
　　　：
    DriverName = "chromedriver"         '2021/9/20 ishi add
End Sub
```

WedDriver.cls への追加

```vba
' ==========================================================================
' Browser Options                       '2021/9/23 add ishi
' ==========================================================================
' DriverName
Private DriverName As String

' Browser specific value
Private browserName_data As String
Private platformName_data As String
Private platform_data As String
Private browserOptions_key As String

' Capabilities, DesiredCapabilities elements
Private extensions As Variant
Private args As Variant
Private Options As New Dictionary
Private alwaysMatch As New Dictionary
Private firstMatchDic As New Dictionary
Private firstMatch As Variant

' Capabilities, DesiredCapabilities
Private MyCapabilities As New Dictionary
Private MyDesiredCapabilities As New Dictionary


' ==========================================================================
' Browser Options                       '2021/9/23 add ishi
' ==========================================================================

' Browser specific value set            '2021/9/23 add ishi
Public Sub CrateOptions()
    If DriverName = vbNullString Then
        Err.Raise 1, "WebDriver.CrateOptions. DriverName is NullString."
    End If
    
    Select Case DriverName
    Case "msedgedriver"
        browserName_data = "MicrosoftEdge"
        platformName_data = "windows"
        platform_data = "WINDOWS"
        browserOptions_key = "ms:edgeOptions"
    Case "chromedriver"
        browserName_data = "chrome"
        platformName_data = "any"
        platform_data = "ANY"
        browserOptions_key = "goog:chromeOptions"
    Case Else
        Err.Raise 2, "WebDriver.CrateOptions. DriverName is Not supported. (" & DriverName & ")"
    End Select
    
    ' Initialize to an empty array
    extensions = Array()
    args = Array()
End Sub

' Add Argument                          '2021/9/23 add ishi
Public Sub addArgument(ByVal argumentdata As String)
    If IsArray(args) Then
        ReDim Preserve args(UBound(args) + 1)
        args(UBound(args)) = argumentdata
    Else
        Err.Raise 3, "WebDriver.addArgument. CrateOptions has not been called."
    End If
End Sub

'Add Option                             '2021/9/23 add ishi
Public Sub addOption(ByVal Key As String, ByVal Data As String)
    If Options.Exists(Key) = False Then
        Options.Add Key, Data
    End If
End Sub

' Build Capabilities                    '2021/9/23 add ishi
Public Property Get BuildCapabilities() As Dictionary
    Options("extensions") = extensions
    Options("args") = args
    
    alwaysMatch("browserName") = browserName_data
    alwaysMatch("platformName") = platformName_data
    If alwaysMatch.Exists(browserOptions_key) = False Then
        alwaysMatch.Add browserOptions_key, Options
    End If
    
    firstMatch = Array(firstMatchDic)
    
    MyCapabilities("firstMatch") = firstMatch
    MyCapabilities.Add "alwaysMatch", alwaysMatch
    
    Set BuildCapabilities = MyCapabilities
End Property

' Build DesiredCapabilities             '2021/9/23 add ishi
Public Property Get BuildDesiredCapabilities() As Dictionary
    Options("extensions") = extensions
    Options("args") = args
   
    MyDesiredCapabilities("browserName") = browserName_data
    MyDesiredCapabilities("version") = ""
    MyDesiredCapabilities("platform") = platform_data
    If MyDesiredCapabilities.Exists(browserOptions_key) = False Then
        MyDesiredCapabilities.Add browserOptions_key, Options
    End If
    
    Set BuildDesiredCapabilities = MyDesiredCapabilities
End Property
```

使い方サンプル１

```vba
    'Browser Setting
    Dim objDrv As WebDriver
    Set objDrv = New WebDriver
    objDrv.Chrome "chromedriver.exe"     'Chromeの場合
    'objDrv.Edge "msedgedriver.exe"      'Edgeの場合
    
    'Browser options
    objDrv.CrateOptions
    objDrv.addArgument "--window-size=1080,400"     'Chrome, Edgeとも、1080*400でブラウザが開く事を確認済
    'objDrv.addArgument "--headless"                'Chrome, Edgeとも、ブラウザ画面が非表示を確認済
    
    'Open Browser
    objDrv.OpenBrowser objDrv.BuildCapabilities, objDrv.BuildDesiredCapabilities
    
    'Navigate URL
    objDrv.Navigate "https://www.yahoo.co.jp/"
    objDrv.Navigate "https://forest.watch.impress.co.jp/"
    
    'Title表示
    MsgBox "page Title : " & objDrv.Title
```

使い方サンプル２

```vba
    'Browser Setting
    Dim objDrv As WebDriver
    Set objDrv = New WebDriver
    objDrv.Chrome "chromedriver.exe"     'Chromeの場合
    'objDrv.Edge "msedgedriver.exe"      'Edgeの場合
    
    'Browser options
    objDrv.CrateOptions
    objDrv.addOption "debuggerAddress", "127.0.0.1:9222"    'Chrome, Edge共に、既存画面タイトルが取得できた事を確認済
    
    'Open Browser As String
    objDrv.OpenBrowser objDrv.BuildCapabilities, objDrv.BuildDesiredCapabilities
    
    'Title表示
    MsgBox "page Title : " & objDrv.Title
    
    'Navigate URL
    objDrv.Navigate "https://forest.watch.impress.co.jp/"
    
    'Title表示
    MsgBox "page Title : " & objDrv.Title
```

**Comment by ezagdd** [comment]
WebDriver.cls

IEDriverserver対応に伴う箇所は、2021/10/16のコメント箇所になります。
上述の commented1 を吸収してあります。
Modify Method. Edge, Chrome, IE, Start #16の commented3 と共でないとコンパイルエラーになります。


```vba
' ==========================================================================
' Browser Options                       '2021/9/23 add ishi
' ==========================================================================
' DriverName
Private DriverName As String

' Browser specific value
Private browserName_data As String
Private platformName_data As String
Private platform_data As String
Private browserOptions_key As String

' Capabilities, DesiredCapabilities elements
Private extensions As Variant
Private args As Variant
Private Options As New Dictionary
Private alwaysMatch As New Dictionary
Private firstMatchDic As New Dictionary
Private firstMatch As Variant

' Capabilities, DesiredCapabilities
Private MyCapabilities As New Dictionary
Private MyDesiredCapabilities As New Dictionary


' ==========================================================================
' Browser Options
' ==========================================================================

' Browser specific value set            '2021/9/23 add ishi -> 2021/10/16 chg ishi
Public Sub CrateOptions()
    If DriverName = vbNullString Then
        Err.Raise 1, "WebDriver.CrateOptions. DriverName is NullString."
    End If
    
    Select Case DriverName
    Case "msedgedriver"
        browserName_data = "MicrosoftEdge"
        platformName_data = "windows"
        platform_data = "WINDOWS"
        browserOptions_key = "ms:edgeOptions"
    Case "chromedriver"
        browserName_data = "chrome"
        platformName_data = "any"
        platform_data = "ANY"
        browserOptions_key = "goog:chromeOptions"
    Case "IEDriverServer"                           '2021/10/16 add ishi
        browserName_data = "internet explorer"
        platformName_data = "windows"
        platform_data = "windows"
        browserOptions_key = "se:ieOptions"
    Case Else
        Err.Raise 2, "WebDriver.CrateOptions. DriverName is Not supported. (" & DriverName & ")"
    End Select
    
    ' Initialize to an empty array
    extensions = Array()
    args = Array()
End Sub

' Add Argument                          '2021/9/23 add ishi
Public Sub addArgument(ByVal argumentdata As String)
    If IsArray(args) Then
        ReDim Preserve args(UBound(args) + 1)
        args(UBound(args)) = argumentdata
    Else
        Err.Raise 3, "WebDriver.addArgument. CrateOptions has not been called."
    End If
End Sub

'Add Option                             '2021/9/23 add ishi -> 2021/10/16 chg ishi
Public Sub addOption(ByVal Key As String, ByVal Data As Variant)    '2021/10/16 ishi String -> Variant
    If Options.Exists(Key) = False Then
        Options.Add Key, Data
    End If
End Sub

' Build Capabilities                    '2021/9/23 add ishi
Public Property Get BuildCapabilities() As Dictionary
    Options("extensions") = extensions
    Options("args") = args
    
    alwaysMatch("browserName") = browserName_data
    alwaysMatch("platformName") = platformName_data
    If alwaysMatch.Exists(browserOptions_key) = False Then
        alwaysMatch.Add browserOptions_key, Options
    End If
    
    firstMatch = Array(firstMatchDic)
    
    MyCapabilities("firstMatch") = firstMatch
    MyCapabilities.Add "alwaysMatch", alwaysMatch
    
    Set BuildCapabilities = MyCapabilities
End Property

' Build DesiredCapabilities             '2021/9/23 add ishi
Public Property Get BuildDesiredCapabilities() As Dictionary
    Options("extensions") = extensions
    Options("args") = args
   
    MyDesiredCapabilities("browserName") = browserName_data
    MyDesiredCapabilities("version") = ""
    MyDesiredCapabilities("platform") = platform_data
    If MyDesiredCapabilities.Exists(browserOptions_key) = False Then
        MyDesiredCapabilities.Add browserOptions_key, Options
    End If
    
    Set BuildDesiredCapabilities = MyDesiredCapabilities
End Property
```

**Comment by GCuser99** [comment]
This is a very useful code contribution. Thanks!

Since the BuildCapabilities json includes both alwaysMatch (required capabilities) and firstMatch (desired capabilities) sections, then why do we need BuildDesiredCapabilities? That seems redundant to me. 

Also, for scraping purposes, you could consider simplifying to only POST alwaysMatch, and not firstMatch section to only cover basic needs such as requesting the --headless mode argument.

I do think this could be simplified considerably, including your idea for building a separate Capabilities class module...

**Comment by GCuser99** [comment]
Here is a rough attempt at a simplified Capabilities class...

`'first pass at a Capabilities class for TinySeleniumVBA
'This was wriiten to be exposed by the WebDriver class
'Add/modify following lines of code in WebDriver class:
'
'Private objCapabilities As Capabilities 'module level declare
'
'Public Function Capabilities() As Capabilities 'this exposes the Capability object
'    Set Capabilities = objCapabilities
'End Function
'
'Private Sub Class_Initialize()
'    Set objCapabilities = New Capabilities
'End Sub
'
'Add following lines the Edge and Chrome methods, respectively:
'objCapabilities.BrowserName = "msedge"
'objCapabilities.BrowserName = "chrome"

'Modify the following line in OpenBrowser method:
'Set resp = Execute(CMD_NEW_SESSION, Params("capabilities", objCapabilities.Dictionary))
'
'Usage:
'Capabilities must be defined prior to Driver.OpenBrowser call as in:
'
'Driver.Edge "C:\Users\....\msedgedriver.exe"
'Driver.Capabilities.addArgument "--headless"
'Driver.Capabilities.addArgument "--window-size=1080,400"
'Debug.Print Driver.Capabilities.JsonString
'Driver.OpenBrowser
'Driver.Navigate "https://www.google.co.jp/?q=selenium"

Private extensions() As Variant
Private args() As Variant
Private OptionsDict As Dictionary
Private mBrowserName As String
Private CapabilitiesDict As Dictionary

'BrowserName passed by Webdriver.Edge or Webdriver.Chrome
Friend Property Get BrowserName() As String
    BrowserName = mBrowserName
End Property

Friend Property Let BrowserName(ByVal str As String)
    mBrowserName = str
End Property

Public Sub addArgument(ByVal argumentdata As String)
    If UBound(args) > -1 Then
        If Not IsError(Application.match(argumentdata, args, 0)) Then Exit Sub
    End If
    ReDim Preserve args(UBound(args) + 1)
    args(UBound(args)) = argumentdata
End Sub

Public Sub addOption(ByVal key As String, ByVal Data As Variant)
    If OptionsDict.Exists(key) = False Then
        OptionsDict.Add key, Data
    End If
End Sub

Public Sub addExtension(ByVal path As String)
    If UBound(extensions) > -1 Then
        If Not IsError(Application.match(path, extensions, 0)) Then Exit Sub
    End If
    ReDim Preserve extensions(UBound(extensions) + 1)
    extensions(UBound(extensions)) = path
End Sub

Private Sub BuildCapabilities()
    Dim OptionsCloneDict As Dictionary, alwaysMatchDic As Dictionary
    Dim browserOptions_key As String

    Select Case mBrowserName
    Case "msedge"
        browserOptions_key = "ms:edgeOptions"
    Case "chrome"
        browserOptions_key = "goog:chromeOptions"
    Case Else
        MsgBox "something went wrong"
        Exit Sub
    End Select

    Set alwaysMatchDic = New Dictionary
    Set OptionsCloneDict = CloneDictionary(OptionsDict)
    If UBound(extensions) > -1 Then OptionsCloneDict("extensions") = extensions
    If UBound(args) > -1 Then OptionsCloneDict("args") = args
    If OptionsCloneDict.Count > 0 Then
        alwaysMatchDic.Add browserOptions_key, OptionsCloneDict
    End If
    Set CapabilitiesDict = Nothing
    Set CapabilitiesDict = New Dictionary
    
    If alwaysMatchDic.Count > 0 Then
        Set CapabilitiesDict = New Dictionary
        CapabilitiesDict.Add "alwaysMatch", alwaysMatchDic
    End If
End Sub

Public Function JsonString() As String
    BuildCapabilities
    JsonString = JsonConverter.ConvertToJson(CapabilitiesDict, 4)
End Function

Public Function Dictionary() As Dictionary
    BuildCapabilities
    Set Dictionary = CapabilitiesDict
End Function

Private Function CloneDictionary(dict As Dictionary)
    Dim newDict As Dictionary
    Set newDict = New Dictionary
    For Each key In dict.Keys
        newDict.Add key, dict(key)
    Next
    newDict.CompareMode = dict.CompareMode
    Set CloneDictionary = newDict
End Function

Private Sub Class_Initialize()
    extensions = Array()
    args = Array()
    Set OptionsDict = New Dictionary
    Set CapabilitiesDict = New Dictionary
End Sub

Sub Clear()
    Set OptionsDict = Nothing
    Set OptionsDict = New Dictionary
    Set CapabilitiesDict = Nothing
    Set CapabilitiesDict = New Dictionary
    extensions = Array()
    args = Array()
End Sub

Private Sub Class_Terminate()
    Set OptionsDict = Nothing
    Set CapabilitiesDict = Nothing
End Sub
`

**Comment by GCuser99** [comment]
Here is a rough attempt at a Capabilities class:
`
'first pass at a Capabilities class for TinySeleniumVBA
'This was wriiten to be exposed by the WebDriver class
'Add/modify following lines of code in WebDriver class:
'
'Private objCapabilities As Capabilities 'module level declare
'
'Public Function Capabilities() As Capabilities 'this exposes the Capability object
'    Set Capabilities = objCapabilities
'End Function
'
'Private Sub Class_Initialize()
'    Set objCapabilities = New Capabilities
'End Sub
'
'Add following lines the Edge and Chrome methods, respectively:
'objCapabilities.BrowserName = "msedge"
'objCapabilities.BrowserName = "chrome"

'Modify the following line in OpenBrowser method:
'Set resp = Execute(CMD_NEW_SESSION, Params("capabilities", objCapabilities.Dictionary))
'
'Usage:
'Capabilities must be defined prior to Driver.OpenBrowser call as in:
'
'Driver.Edge "C:\Users\....\msedgedriver.exe"
'Driver.Capabilities.addArgument "--headless"
'Driver.Capabilities.addArgument "--window-size=1080,400"
'Debug.Print Driver.Capabilities.JsonString
'Driver.OpenBrowser
'Driver.Navigate "https://www.google.co.jp/?q=selenium"
'
'The following is print in immediate window:
'{
'    "alwaysMatch": {
'        "ms:edgeOptions": {
'            "args": [
'                "--headless",
'                "--window-size=1080,400"
'            ]
'        }
'    }
'}


Private extensions() As Variant
Private args() As Variant
Private OptionsDict As Dictionary
Private mBrowserName As String
Private CapabilitiesDict As Dictionary

'BrowserName passed by Webdriver.Edge or Webdriver.Chrome
Friend Property Get BrowserName() As String
    BrowserName = mBrowserName
End Property

Friend Property Let BrowserName(ByVal str As String)
    mBrowserName = str
End Property

Public Sub addArgument(ByVal argumentdata As String)
    If UBound(args) > -1 Then
        If Not IsError(Application.match(argumentdata, args, 0)) Then Exit Sub
    End If
    ReDim Preserve args(UBound(args) + 1)
    args(UBound(args)) = argumentdata
End Sub

Public Sub addOption(ByVal key As String, ByVal Data As Variant)
    If OptionsDict.Exists(key) = False Then
        OptionsDict.Add key, Data
    End If
End Sub

Public Sub addExtension(ByVal path As String)
    If UBound(extensions) > -1 Then
        If Not IsError(Application.match(path, extensions, 0)) Then Exit Sub
    End If
    ReDim Preserve extensions(UBound(extensions) + 1)
    extensions(UBound(extensions)) = path
End Sub

Private Sub BuildCapabilities()
    Dim OptionsCloneDict As Dictionary, alwaysMatchDic As Dictionary
    Dim browserOptions_key As String

    Select Case mBrowserName
    Case "msedge"
        browserOptions_key = "ms:edgeOptions"
    Case "chrome"
        browserOptions_key = "goog:chromeOptions"
    Case Else
        MsgBox "something went wrong"
        Exit Sub
    End Select

    Set alwaysMatchDic = New Dictionary
    Set OptionsCloneDict = CloneDictionary(OptionsDict)
    If UBound(extensions) > -1 Then OptionsCloneDict("extensions") = extensions
    If UBound(args) > -1 Then OptionsCloneDict("args") = args
    If OptionsCloneDict.Count > 0 Then
        alwaysMatchDic.Add browserOptions_key, OptionsCloneDict
    End If
    Set CapabilitiesDict = Nothing
    Set CapabilitiesDict = New Dictionary
    
    If alwaysMatchDic.Count > 0 Then
        Set CapabilitiesDict = New Dictionary
        CapabilitiesDict.Add "alwaysMatch", alwaysMatchDic
    End If
End Sub

Public Function JsonString() As String
    BuildCapabilities
    JsonString = JsonConverter.ConvertToJson(CapabilitiesDict, 4)
End Function

Public Function Dictionary() As Dictionary
    BuildCapabilities
    Set Dictionary = CapabilitiesDict
End Function

Private Function CloneDictionary(dict As Dictionary)
    Dim newDict As Dictionary
    Set newDict = New Dictionary
    For Each key In dict.Keys
        newDict.Add key, dict(key)
    Next
    newDict.CompareMode = dict.CompareMode
    Set CloneDictionary = newDict
End Function

Private Sub Class_Initialize()
    extensions = Array()
    args = Array()
    Set OptionsDict = New Dictionary
    Set CapabilitiesDict = New Dictionary
End Sub

Sub Clear()
    Set OptionsDict = Nothing
    Set OptionsDict = New Dictionary
    Set CapabilitiesDict = Nothing
    Set CapabilitiesDict = New Dictionary
    extensions = Array()
    args = Array()
End Sub

Private Sub Class_Terminate()
    Set OptionsDict = Nothing
    Set CapabilitiesDict = Nothing
End Sub



`

**Comment by GCuser99** [comment]
Added Preferences Option to Capabilities Class above...

**Comment by uezo** [comment]
@ezagdd @GCuser99 Thank you for your kind contributions🥰

As @GCuser99 mentioned the usage below is developer-friendly I think.

```vba
Driver.Edge "C:\Users\....\msedgedriver.exe"
Driver.Capabilities.Add "acceptInsecureCerts", False
Driver.Capabilities.AddArgument "--headless"
Driver.Capabilities.AddArgument "--window-size=1080,400"

Driver.OpenBrowser
Driver.Navigate "https://www.google.co.jp/?q=selenium"
```

TODO:
- Add `Capabilities` to WebDriver and use it when open browser
- Overwrite `Capabilities` when `OpenBrowser()` received `capabilities` argument
- Make `desiredCapabilities` argument for `OpenBrowser()` deprecated at this time as the official bindings do so
- Add some shortcut methods/properties to configure frequently used options (headless and something)

**Comment by GCuser99** [comment]
As far as your last item in your TODO list, here are two shortcuts that I'm using:

```
Public Sub SetDownloadPrefs(ByVal downloadDirectoryPath, Optional userPrompt As Boolean = False)
    downloadDirectoryPath = GetAbsolutePath(downloadDirectoryPath)
    'these work for both Chrome and Edge
    Me.Capabilities.AddPref "download.default_directory", downloadDirectoryPath
    Me.Capabilities.AddPref "download.directory_upgrade", True
    Me.Capabilities.AddPref "download.prompt_for_download", userPrompt 'false disables prompting user for download permission
    Me.Capabilities.AddPref "safebrowsing.enabled", True
End Sub

Public Sub SetBrowserVisibilty(ByVal val As Boolean) 
    If val Then
        Me.Capabilities.RemoveArgument "--headless"
    Else
        Me.Capabilities.AddArgument "--headless"
    End If
End Sub

```

**Comment by GCuser99** [comment]
Another idea is to make the above methods of the Capabilities class instead of the WebDriver class...

**Comment by ezagdd** [comment]
@uezo @GCuser99
Capabilities, DesiredCapabilitiesは、クラスを新たに作らずにTinySeleniumVBAで提供されているクラス内で、テスト的に作成したものです。より使いやすい様になる事を期待します。

@uezo @GCuser99
Capabilities and DesiredCapabilities were created as a test in the class provided by TinySeleniumVBA without creating a new class. We hope this will make it easier to use.

**Comment by GCuser99** [comment]
@uezo, as far as some short-cut capabilities that you mentioned above, I think it would be good to allow an optional "invisible" flag in the OpenBrowser method since that would (at least for me) be a common usage case... Something like this below - what do you think?
```
' Open browser
Public Function OpenBrowser(Optional caps As Capabilities, Optional ByVal invisible As Boolean = False, Optional ByVal useAsDefaultSession As Boolean = True) As String
    Dim resp As Dictionary
    
    If caps Is Nothing Then
        Set caps = Me.CreateCapabilities
    End If
        
    If invisible Then
        'user may have already added headless, but selenium doesn't seem to care about multiple arg entries
        caps.AddArgument "--headless"
    End If
    
    Set resp = Execute(CMD_NEW_SESSION, Params("capabilities", caps.Dictionary))("value")
    
    If useAsDefaultSession Then
        DefaultSessionId = resp("sessionId")
    End If
    
    OpenBrowser = resp("sessionId")
    
End Function
```
