### ISSUE TITLE
Chrome Driver in Headless Mode?

### ISSUE THREAD

**Issue by GCuser99** [uezo/TinySeleniumVBA#37]
This is an awesome code resource - thank-you!

The Selenium Chrome driver takes an option "--headless" which puts the browser into invisible mode. How do we add options capability  using the Webdriver class?

**Comment by GCuser99** [comment]
Oh, I see that my question was addressed in https://github.com/uezo/TinySeleniumVBA/issues/28 below...

Thanks.

**Comment by uezo** [comment]
@GCuser99 Thank you for your self support!
I will update repo by the end of the year to apply the changes of pull request.
