### ISSUE TITLE
Not working after Chrome Driver version 127 on Chrome 128?

### ISSUE THREAD

**Issue by mcodr** [uezo/TinySeleniumVBA#76]
Anyone else having issues with new version of Chrome Driver 128.X.XXX.XX with Chrome 128?
Code seems to work fine when I use Chrome Driver 127.0.6533.XX with Chrome 128 otherwise.

Error comes after Driver.OpenBrowser Cap

Error message: "A connection with the server could not be established"

**Comment by mcodr** [comment]
Checking https://issues.chromium.org/issues?q=status:open%20componentid:1608258&s=created_time:desc for any relevant workarounds, so far none :/

**Comment by GCuser99** [comment]
Here is the issue:
https://chromium.googlesource.com/chromium/src/+/6f33d75f071e322c4a3e49b0a4ac2022e5b6cada

One way to solve is to explicitly specify the --port=9515 argument in the Shell command string in the Start method of WebDriver class.

**Comment by mcodr** [comment]
> Here is the issue: https://chromium.googlesource.com/chromium/src/+/6f33d75f071e322c4a3e49b0a4ac2022e5b6cada
> 
> One way to solve is to explicitly specify the --port=9515 argument in the Shell command string in the Start method of WebDriver class.

Hi GCuser99, thanks for staying active.
But I am afraid I have already tried this and still getting the same issue. 
Chromedriver would just not start.

This part right here in OpenBrowser() function in WebDriver.cls is where it fails:
Set resp = Execute(CMD_NEW_SESSION, Params("capabilities", capDict, "desiredCapabilities", desiredCapabilities))

What i basically have already tried is:
cap.AddArgument "--headless --port=9515"

Run-time error: A connection with the server could not be established

**Comment by GCuser99** [comment]
As I said before, you need to explicitly set the port to 9515 when the connection with ChromeDriver is established in the Start method. Then you should be able to verify in the command line window that the port was set properly. Trying to set the port with capabilities is too late - you are sending commands to a connection that does not exist.

**Comment by mcodr** [comment]
You're the best!
